### ISSUE TITLE
merge fork?

### ISSUE THREAD

**Issue by berot3** [linanwx/aosr#31]
Hi! 

I really like this plugin as an alternative to the spaced repetition plugin!

But one of the first things I noticed was this fork by @hedyhli : https://github.com/hedyhli/aosr

Just wondering if it would make sense to maybe merge his changes? He did make some good contributions which make sense, but maybe you can comment them:

> CHANGES from the original Aosr
> 
> - Make back of the card and clozes transparent rather than blurred. This **eliminates hinting** the user on how the answer roughly looks like
> - (unstable) Use the [Obsidian Text-To-Speech Plugin](https://github.com/joethei/obsidian-tts) API to automatically speak each card's content (both front and back) if the TTS URL setting is not null
> - Rearranged buttons and UI elements
> - Shuffles all cards before review
> - Hides the "#multicloze" tag for a card during review
> - Updates grammar and wording (personal preference)
> - Changed the "Waiting Timeout Basevalue" setting input to use text field rather than obsidian slider

**Comment by hedyhli** [comment]
Hi, unfortunately my fork hasn't been very up to date since I've switched from obsidian to logseq, so I am not even sure if the changes are relevant anymore. However if linanwx is ok with merging these changes I am happy to work on getting them up to date and open PR(s)

**Comment by linanwx** [comment]
Thank you for your feedback on the Aosr project.

1. I am aware of @hedyhli's fork and have reviewed the changes. Key updates like hiding the "#multicloze" tag during card review have already been implemented in the main branch.
2. Regarding the modifications for fuzzy answers, I have adjusted the level of fuzziness to a higher degree to prevent any hinting at the answers.
3. Some changes, such as those related to TTS pronunciation, require extensive work, especially since our current system only supports English. For a comprehensive solution, we would need to recognize different languages and adopt appropriate pronunciations. This might involve integrating interfaces from generative AI, like ChatGPT or more cost-effective options.
4. Given these considerations, a merge with the fork does not seem necessary at this stage.

I appreciate your engagement and look forward to further discussions on how we can enhance Aosr.

**Comment by berot3** [comment]
thanks a lot! I think its good that we talked about this :D

> 2. Regarding the modifications for fuzzy answers, I have adjusted the level of fuzziness to a higher degree to prevent any hinting at the answers.

Maybe still add in a option to toggle/control this? I personally don't like the blur much, but I am getting used to it :)

---

What about 
> Shuffles all cards before review

is this done now?
